spring:
  application:
    name: adblock-manager

  datasource:
    url: jdbc:mysql://localhost:3306/adblock?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: userexample
    password: 0000
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
